version: '3.3'

services:
  notifyme:
    container_name: notifyme
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
    ports:
      - 5000:5000
    environment:
      - APP_CONFIG=notifyme.config.DevelopmentConfig
      - FLASK_APP=/usr/src/app/autoapp.py
      - FLASK_DEBUG=1
